### ISSUE TITLE
Switch from ALchemy to DSOAL/OpenAL Soft

### ISSUE THREAD

**Issue by VoidsShadow** [yumiris/Eaxir#1]

**Comment by yumiris** [comment]
Can certainly be done. Got some reputable links for the binaries?

**Comment by yumiris** [comment]
Can certainly be done. Got some reputable links for the binaries?

**Comment by VoidsShadow** [comment]
[Vaporeon typically compiles and hosts the latest binaries on his website.](http://vaporeon.io/hosted/dsoal-builds/).

**Comment by yumiris** [comment]
Perfect, thank you! It seems like the archive only contains the DLLs. Are there any specific configurations which need to be set up, akin to dsound.ini?

**Comment by SubhadeepJasu** [comment]
I have no idea how it works.

**Comment by VoidsShadow** [comment]
@SubhadeepJasu 
[alsoft-reference.txt](https://github.com/yumiris/HCE.Eaxir/files/2929018/alsoft-reference.txt)
This is the ini with all the documentation present.

**Comment by VoidsShadow** [comment]
I randomly stumbled upon the configuration tool for DSOAL. It's included with the [OpenAL-Soft Windows binaries](https://openal-soft.org/#download). I have yet to learn if it accepts a working directory argument. By default, it reads and writes to the system-wide, user-specific config file, %appdata%/alsoft.ini.

**Comment by yumiris** [comment]
That is absolutely perfect. I'll have the [loader](https://github.com/yumiris/SPV3.CLI/) enable EAX with DSOAL, and copy the user-config file from `%appdata%/alsoft.ini` when running SPV3/HCE. That should keep things nice and compatible with both HCE & the tool you've linked.

**Comment by yumiris** [comment]
In light of the above, a dedicated issue has been created to discuss this topic further more: https://github.com/yumiris/SPV3.CLI/issues/11

**Comment by VoidsShadow** [comment]
Because basic support for dsoal has been implemented, this issue is now closed.

However, users who are not familiar with alsoft's ini configuration may appreciate being informed of alsoft-config, which is packaged with mainline releases of alsoft.
